<div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                              
                                


                                <div class="card">
                                    <div class="card-header">
                                        <center>
                                        <strong>Buscar Medicamentos</strong>
                                    </center>

                                  

                                    </div>
<div class="card-body card-block">

<form method="POST">
  <div class="form-group">
    <label for="buscar">Ingrese medicamento que desea buscar</label>
    <input type="text" class="form-control" id="buscar" placeholder="Ingrese nombre de la escuela">

  </div>
  
</form>

<table id="table" class="display">
<thead>

<tr>
<th>Nombre Farmacia</th>
<th>Numero de registro</th>

<th>Acción</th>

</tr>


</thead>

<tbody>




</tbody>


</table>



                                    
</div>


                                    




                                    <div class="card-footer">
                                       
                                    </div>
                                </div>










                            </div>
                            
                        </div>

                        </div>



<script>


$("#buscar").on("keyup",function(){
    var bus=$("#buscar").val();
if(bus.length>=2){
    console.log(bus);
$.ajax({
url:"buscar/busqueda/",
type:'POST',
data:{'bus':bus},
success:function(resultado){

$("#table").DataTable().destroy();
$("#table tbody").html(resultado);
      $('#table').DataTable({
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ],
        responsive: true,rowReorder: {
            selector: 'td:nth-child(2)'
        },
        "language":{
            "sSearch":"Buscar",
            "lengthMenu":"Mostrar _MENU_ registros",
            "infoEmpty":"Mostrando registros del 0 al 0 de un total de 0 registros",
            "zeroRecords":"No se encuentran resultados",
            "info":"Mostrando registros del _START_ al _END_ de un _TOTAL_ de registros",
            "oPaginate":{
                "sNext":"Siguiente",
                "sPrevious":"Anterior"
            }        
        }
        
        }); 


}  
});
}
else if(bus.length==0){
    $("#table").DataTable().destroy();
    $("#table tbody").empty();
      $('#table').DataTable({
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ],
        responsive: true,rowReorder: {
            selector: 'td:nth-child(2)'
        },
        "language":{
            "sSearch":"Buscar",
            "lengthMenu":"Mostrar _MENU_ registros",
            "infoEmpty":"Mostrando registros del 0 al 0 de un total de 0 registros",
            "zeroRecords":"No se encuentran resultados",
            "info":"Mostrando registros del _START_ al _END_ de un _TOTAL_ de registros",
            "oPaginate":{
                "sNext":"Siguiente",
                "sPrevious":"Anterior"
            }        
        }
        
        }); 
}





    
    });

    </script>



