<!-- 
<div class="row">
<div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">

</div>
</div>
-->

<div class="row">

<div id="map" style="width: 100%; height: 500px;"></div>

</div>



<script>

var direccion =[13.484738862743582, -86.58146656360756];
    var map = L.map('map').setView(direccion, 13);

    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">FarmApp</a>'
    }).addTo(map);

    
var ubicaciones=JSON.parse('<?= $this->datos ?>');
console.log(ubicaciones);

for (i=0;i<ubicaciones.length;i++){
    var icono=L.icon({iconUrl:'http://localhost/FarmApp/Views/plantilla/assets/img/ubic-icon.png'});
    marcador=L.marker([ubicaciones[i]['latitud'],ubicaciones[i]['longitud']],{icon: icono}).addTo(map);
    marcador.bindPopup([ubicaciones[i]['nombre']]+'. <br> Ubicada en: '+[ubicaciones[i]['direccion']]);
    //.bindPopup('Farmacia. +"ubicaciones[i]['nombre']+" A pretty CSS popup.<br> Easily customizable.');
    
    console.log(ubicaciones[i]['longitud']);
    console.log(ubicaciones[i]['nombre']);
    console.log(ubicaciones[i]['latitud']);
    lat=ubicaciones[i]['longitud'];
    long=ubicaciones[i]['latitud'];
    console.log(lat);
    console.log(long);

   // L.marker(ubicaciones[i]['latitud'],ubicaciones[i]['longitud']).addTo(map);
    //L.marker([long,lat]).addTo(map);
}


    //var icono=L.icon({iconUrl:'http://localhost/FarmApp/Views/plantilla/assets/img/ubic-icon.png'});
   // L.marker(direccion,{icon: icono}).addTo(map);


</script>
